services:
  # Frontend service override for tests - use internal Docker network
  frontend:
    environment:
      - VITE_API_URL=http://backend:8000

  # Backend Unit Test Runner
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      sh -c "pip install -r backend/requirements.txt &&
             pip install pytest pytest-asyncio httpx &&
             PYTHONPATH=/app pytest tests/ -v"
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
    networks:
      - medical-network

  # Frontend Unit Tests
  frontend-tests:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      sh -c "npm install && npm run test"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - medical-network

  # Playwright E2E Tests
  e2e-tests:
    image: mcr.microsoft.com/playwright:v1.55.0-jammy
    working_dir: /app
    command: >
      sh -c "npm install &&
             ./scripts/wait-for-frontend.sh &&
             npx playwright test"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
      - frontend
    networks:
      - medical-network

  # e2e-tests-real 
  e2e-tests-real:
    image: mcr.microsoft.com/playwright:v1.55.0-jammy
    working_dir: /app
    environment:
      - APP_URL=http://frontend:8081   # used by global-setup + baseURL
      - CI=1
    command: >
      sh -c "npm install &&
             ./scripts/wait-for-frontend.sh &&
             npx playwright test -c playwright.e2e-real.config.ts"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
      - frontend
    networks:
      - medical-network


networks:
  medical-network:
    driver: bridge
