// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzcbfoyeronncccedhap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Y2Jmb3llcm9ubmNjY2VkaGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzQ4NDIsImV4cCI6MjA2OTY1MDg0Mn0.R1NZuBDECcO-IeYVb95PvZ902HQQBQFTeplp7pekUaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});